---
# tasks file for docker-ce
- name: install docker requirment
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip

- name: "download Docker’s official GPG key"
  command:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg  -o docker.gpg"

- name: unpack docker ASCII armor
  command:
    cmd: "sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg  --yes ./docker.gpg"

- name: "Add Docker’s sources.list"
  template:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: install docker-ce
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: docker-ce enable now
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: test docker work good
  command:
    cmd: "docker run hello-world"
  register: docker_helloworld

- name: test docker work good
  debug:
    msg: "{{ docker_helloworld }}"
