# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# box 來源
  config.vm.box = "ubuntu.box"
# box 驗證方式
  config.ssh.username = "owan"
  config.ssh.password = "P@ssw0rd"  

# 設定 VM 資源及使用 link clone 節省 host 空間  
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 2
  end

# 使用迴圈建立大量 VM
	(1..1).each do |i|
		# Defining VM properties
		config.vm.define "lab_vm#{i}" do |node|
			node.vm.hostname = "node#{i}.local"
			node.vm.network "public_network", ip: "192.168.15.#{140+i}"
		    end
		
       config.vm.provision "shell",
       run: "always",
       inline: "sudo ip route del default"
		
		config.vm.provision "shell",
       run: "always",
       inline: "sudo ip route add default via 192.168.15.1 "
		
		end



# 建立單一VM
#config.vm.define "rockylinux_mgmt" do |mgmt|
#  mgmt.vm.hostname = "mgmt.local"
## 設定 public 網卡，讓 host 能夠連線
#  mgmt.vm.network "public_network", ip: "192.168.15.100"
#end
end
