---
- name: apply common 、 ssh-copy-id configuration to all nodes
  hosts: all
 # remote_user: root
  roles:
    - ssh-copy-id
    - common

- name: apply selinux configuration to all nodes
  hosts: all
 # remote_user: root
  roles:
    - selinux
  vars: 
    selinux_config: enforcing