---
# Handler to handle DB tier notifications

- name: restart mysql
  systemd:
    name: mysqld
    state: restarted

- name: restart iptables
  service:
    name: iptables
    state: restarted
