# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# box 來源
  config.vm.box = "rockylinux.box"
# box 驗證方式
  config.ssh.username = "root"
  config.ssh.password = "P@ssw0rd"  

# 設定 VM 資源及使用 link clone 節省 host 空間  
  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 2
  end

# 使用迴圈建立大量 VM
	(1..3).each do |i|
		# Defining VM properties
		config.vm.define "rockylinux_vm#{i}" do |node|
			node.vm.hostname = "node#{i}.local"
			node.vm.network "public_network", ip: "192.168.15.14#{i}"
		end
	end

## 建立單一VM
#  config.vm.hostname = "node1.local"
## 設定 public 網卡，讓 host 能夠連線
#  config.vm.network "public_network", ip: "192.168.15.141"

end
